### ISSUE TITLE
Faling to connect

### ISSUE THREAD

**Issue by danieledge** [jeffreydwalter/arlo#10]
Hi,

I've getting the error 
EOF occurred in violation of protocol (_ssl.c:590) or sometimes ('Connection aborted.', error(54, 'Connection reset by peer'))

Any ideas?

Thanks!

**Comment by jeffreydwalter** [comment]
Can you please provide a little more detail. A code snippet that reproduces the issue would be great.

**Comment by cmsj** [comment]
I can reproduce this, I'm on macOS (latest Sierra) and just running your example code for arming the basestation. With reference to https://www.ssllabs.com/ssltest/analyze.html?d=arlo.netgear.com&s=54.229.136.60 and https://github.com/kennethreitz/requests/issues/3006 and the output of `openssl version` (0.9.8zh) I think this is probably because the version of OpenSSL on macOS doesn't support TLS1.2, and that's the only protocol that `arlo.netgear.com` supports.

I don't have a solution yet though, sorry!

**Comment by jeffreydwalter** [comment]
Hey @cmsj,

Thanks for the input! I was JUST reading through that exact same issue (kennethreitz/requests#3006) in the requests library, and came to the same basic conclusion. :)
 
 @danieledge what @cmsj said is most likely your culprit. If you're on a mac, you should follow the instructions [here](https://comeroutewithme.com/2016/03/13/python-osx-openssl-issue/) to update your openssl library.
