### ISSUE TITLE
Ticket to track my progress on updates

### ISSUE THREAD

**Issue by howdydoody123** [jeffreydwalter/arlo#5]
Apparently you can't have issues on forks. I want to keep you in the loop on the things I'm doing to the library so that once you get the pull request it isn't overwhelming.

[This is my latest commit](https://github.com/ThaWeatherman/arlo/commit/a12e6d94d87ac31ba3f1ecbb1c918abca9382c77). You can see a lot of the changes reflected there.

I have not integrated your EventStream changes yet. I want to ensure this base functionality works before continuing on to the more advanced streaming calls.

What this has all taught me is that Netgear doesn't know how to write a proper API :D

**Comment by jeffreydwalter** [comment]
Hey! Thanks for the heads-up.

I reviewed your changes and it all looks really good, so thanks for all the hard work!

Netgear definitely has some strange ideas about what an API should be. It seems to me that they built this API specifically to meet the needs of the browser and their web app, thus the EventStream crap.

I noticed that you combined BatchDeleteRecordings() and DeleteRecording() into delete_recordings(). Does delete_recordings() require an [] of {}s or can you just pass a {} to delete a single recording?

**Comment by howdydoody123** [comment]
You can pass a single recording in the list. Both calls looks the same from what I could tell. I haven't added a test for that function yet. I've pushed another commit with tests laid out for each method, though they aren't necessarily all complete. If you see a test filled out in `tests/test.py` though then that call is confirmed as working.

I got a 400 on the streaming method, so I need to figure out what's wrong with the call. Also, do you know what the `reset` method is for? I've only noticed it getting called after I deleted recordings in the browser.

**Comment by howdydoody123** [comment]
@jeffreydwalter How did you come up with the transId formula? Is it absolutely necessary? I'm trying to get streaming to work but to no avail.

**Comment by jeffreydwalter** [comment]
I converted their JavaScript implementation. Is absolutely necessary. It's
required to identify and correlate the asynchronous EventSteam instances.

**Comment by jeffreydwalter** [comment]
I forget what reset does. It's been a while. :)

On Jan 18, 2017 8:17 PM, "Sean Beck" <notifications@github.com> wrote:

You can pass a single recording in the list. Both calls looks the same from
what I could tell. I haven't added a test for that function yet. I've
pushed another commit with tests laid out for each method, though they
aren't necessarily all complete. If you see a test filled out in
tests/test.py though then that call is confirmed as working.

I got a 400 on the streaming method, so I need to figure out what's wrong
with the call. Also, do you know what the reset method is for? I've only
noticed it getting called after I deleted recordings in the browser.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jeffreydwalter/arlo/issues/5#issuecomment-273555932>,
or mute the thread

**Comment by schas002** [comment]
> Apparently you can't have issues on forks.

Or can you?

[![Screenshot_2017-03-03-08-17-09.png](https://s6.postimg.org/rvk44ayz5/Screenshot_2017_03_03_08_17_09.png)](https://postimg.org/image/6lwhtgiod/)

**Comment by howdydoody123** [comment]
@schas002 I guess Github likes you more.

![capture](https://cloud.githubusercontent.com/assets/2522737/23611043/52af3356-0243-11e7-8149-1f325a30bf14.PNG)

**Comment by schas002** [comment]
@ThaWeatherman in Settings, check Features ==> Issues. Anyone can do that on any fork they own.

**Comment by howdydoody123** [comment]
@schas002 Ah there it is. Thanks.

**Comment by jeffreydwalter** [comment]
@ThaWeatherman you still working on this?

**Comment by howdydoody123** [comment]
@jeffreydwalter it's been a while. too much going on at the moment. i haven't forgotten about it though

**Comment by howdydoody123** [comment]
@jeffreydwalter maybe one day they'll just have a public API for us to use and i can write a wrapper for that
