### ISSUE TITLE
Feature request: Camera Disconnect Warning 

### ISSUE THREAD

**Issue by asispardo** [jeffreydwalter/arlo#86]
First of all, my apologies if this is not the correct place to post this.

I have lately been comparing my Arlo system to more professional alarm systems. There are two main differences regarding security:
- The "service" component, meaning the human team behind the professional alarm
- The anti-inhibition features

This second issue is usually just a continuous "i'm still alive" ping that, if interrupted, triggers a warning. I believe this should be available in ARLO, but for some reason, it isn't.

For what I've seen (I might be mistaken), there is no way to check the status (available/reachable vs disconnected) of an individual camera. If this were available, a simple script could periodically check that all cameras are connected, making the system aware of a DEAUTH attack on the camera wifi network. This script, run from off-site, would be able to throw a warning.

This would contribute enormously to the security of our ARLO systems (which now are ridiculously vulnerable to anyone with a network adapter with monitor mode capability).

Thanks!!
Asis

**Comment by jeffreydwalter** [comment]
You are able to get status for each camera using this library. So you could, a) periodically poll the device status, using `GetCameraState()` (see https://github.com/jeffreydwalter/arlo/blob/master/Arlo.py#L467-L472), to determine if it becomes disconnected, or b) use the `HandleEvents()` method (see https://github.com/jeffreydwalter/arlo/blob/master/Arlo.py#L416) to process incoming events from the EventStream. I believe the EventStream receives a message if a camera goes offline. (Haven't confirmed that an event is actually sent, but I believe it to be a fact.)

**Comment by jeffreydwalter** [comment]
That being said, I'm not aware of any DEAUTH attacks on Arlo cameras. Do you have a working POC for this type of attack?

**Comment by asispardo** [comment]
Hi,

Thank you for your response! I will look into your comments (polling and
events).

Regarding the deauth attack, I haven't tried it (it's on my -rather long-
to do list), but I am quite sure it would work. The cameras are connected
through a conventional wifi, so if you bombard the cameras with deauth
packages (like you can do with the aircrack-ng suite) I don't see how they
could send any video, and to my knowledge arlo doesn't notice or if it does
it doesn't send notifications.

Just as a comment, to make the system secure the polling would have to be
made from off site. That would also protect from a cut internet connection
(although it could have many false positives).

Lastly, congrats and thank you for your work on this library. It has been
very useful!

Thanks,
Asis

**Comment by jeffreydwalter** [comment]
The cameras aren't connected directly to the network (at least not the model I have). They are connected to a basestation over some proprietary protocol (but who knows, it could be a standard protocol). It's recommended that you connect the basestation via ethernet, which would preclude over the air attacks, like you're describing.
That being said, I assume the connection between the cameras and the basestation is encrypted, but I've never bothered to attempt to inspect the traffic, so who knows.

If your internet is cut, then your cameras aren't going to work (unless you use the Arlo Go which have cellular connections) because they require an internet connection to send messages and data (snapshots and recordings) to the Arlo servers where they are stored.

Ultimately, the Arlo cameras aren't really a "security" product. They are better suited (imo) for casual monitoring of stuff. If you need commercial grade security, you probably want to use IP cameras, a NAS (for local storage), and some cloud backup solution (for offsite backup) for 24/7 recording and some 3rd party service for monitoring.

Good luck!

**Comment by asispardo** [comment]
I believe the cameras connect to the base station via wifi, with a hidden
ssid (you should be able to see it with a simple app in your phone such as
"wifi analyzer"). The traffic is indeed encrypted, as with any password
protected wifi, so it can't be snooped on, but the connection can most
probably be broken easily.

With this polling, the product could be quite secure. The technology is not
very different from any regular security alarm.

Thanks!

**Comment by jeffreydwalter** [comment]
Thanks for the input! Sounds like you're right! https://community.arlo.com/t5/Arlo-Pro/How-does-Arlo-pro-base-station-and-cameras-communicate/td-p/1237568

Any contributions you can make in this area (sample scripts or whatever) would be greatly appreciated!

Cheers!
