### ISSUE TITLE
refresh access token

### ISSUE THREAD

**Issue by jijoamt** [jeffreydwalter/arlo#94]
Is there an API with which we can  refresh the access token and what is the expiry period of the access token

**Comment by jeffreydwalter** [comment]
@jijoamt to my knowledge there's not an API explicitly for refreshing the access token. That token is issued when you login. If you need to refresh it, you can `Login()` again. I do know that the Arlo API only allows a single login at a time because they use an EventStream API that doesn't support broadcasting.

**Comment by jeffreydwalter** [comment]
*when I say they only allow one login at a time, what I mean is that if you login in two places, the first logged in client will be logged out.
